<?php
include'../dbconnect.php';
include 'razorpay-php/Razorpay.php';
 //$apiKey = "rzp_test_YxfkUbFXwfG4Vc";
 use Razorpay\Api\Api;


$keyId = 'rzp_test_9RzFxChAkkAoJg';
$secretKey =  'sM3qTwUpvA99SzYYwSWfnO3C';
$api = new Api($keyId, $secretKey);

$uid=$_POST['uid'];
$galleryid=$_POST['galleryid'];
$amount=$_POST['amount'];
$firstname=$_POST['firstname'];
$dat=date('Y-m-d');
$contno=$_POST['contno'];
$email_id=$_POST['email_id'];
$paise=$amount*100;

$order= $api->order->create(array(
'receipt'=>rand(1000,9999).'ORD',
'amount'=>$paise,
'payment_capture'=>1,
'currency'=>'INR',)
);
?>


<meta name="viewport" content="width=device-width">
<form action="payments_insert.php" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $keyId; ?>" // Enter the Test API Key ID generated from Dashboard ? Settings ? API Keys
    data-amount="<?php echo $order->amount; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ?299.35.
    data-currency="INR"//You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="<?php echo $order->id ?>"//Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Modern Art Wing"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://www.clipartmax.com/png/middle/356-3568187_justice-law-logo-template-vector.png"
    data-prefill.name="<?php echo $firstname;  ?>"
	data-prefill.contact="<?php echo $contno;  ?>"
    data-prefill.email="<?php echo $email_id ?>"
    data-theme.color="#0efbda"
></script>
<input type="hidden" custom="Hidden Element" name="hidden">
<input type="hidden" name="uid" value="<?php echo $uid; ?>">
<input type="hidden" name="galleryid" value="<?php echo $galleryid; ?>">
<input type="hidden" name="amount" value="<?php echo $amount; ?>">
<input type="hidden" name="dat" value="<?php echo $dat; ?>">
<input type="hidden" name="contno" value="<?php echo $contno; ?>">

</form>
